# Generated by Django 5.0.3 on 2024-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
